version: '3.9'

networks:
  broadcast_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  manager:
    build: .
    command: ["java", "-cp", "build/classes/java/main", "ru.nsu.pozhidaev.manager.Manager"]
    networks:
      broadcast_net:
        ipv4_address: 172.28.0.10

  worker1:
    build: .
    command: ["java", "-cp", "build/classes/java/main", "ru.nsu.pozhidaev.worker.Worker"]
    networks:
      broadcast_net:
        ipv4_address: 172.28.0.11

  worker2:
    build: .
    command: ["java", "-cp", "build/classes/java/main", "ru.nsu.pozhidaev.worker.Worker"]
    networks:
      broadcast_net:
        ipv4_address: 172.28.0.12