plugins {
    id 'java'
    id 'jacoco'
    id 'checkstyle'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'ru.nsu.pozhidaev'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation 'com.fasterxml.jackson.core:jackson-databind:2.16.1'

    implementation 'org.openjfx:javafx-controls:21'
    implementation 'org.openjfx:javafx-fxml:21'

    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
}

run {
    jvmArgs = [
            "--module-path", "${classpath.asPath}",
            "--add-modules", "javafx.controls,javafx.fxml"
    ]
}

application {
    mainClass = 'ru.nsu.pozhidaev.Main'
}


test {
    useJUnitPlatform()
}

checkstyle {
    toolVersion = '10.3'  // Версия Checkstyle
    configFile = file('../.github/google_checks.xml')
}

tasks.withType(Checkstyle) {
    reports {
        xml.required.set(false)
        html.required.set(true)
    }
}

javafx {
    version = "23.0.2"
    modules = [ 'javafx.controls' ]
}

jacocoTestReport {
    reports {
        xml.required = true
    }
}